# -*- mode: ruby -*-
# vi: set ft=ruby :

# Generate the token needed for a node to join the cluster
require 'securerandom'
random_string1 = SecureRandom.hex
random_string2 = SecureRandom.hex
cluster_init_token = "#{random_string1[0..5]}.#{random_string2[0..15]}"


# Set global variables
NUM_NODES = 2           # number of Slave nodes to be generated
MASTER_CPU = 2          # Master's CPUs number
MASTER_MEM = 4096       # Master's memory size
SLAVE_CPU = 2           # Slaves' CPUs number
SLAVE_MEM = 2048        # Slaves' memory size
START_IP = "192.168.0.2"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # start from a basic Ubuntu 18.04 server
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  # apply the generic configuration script to disable the swap, install docker 
  # and kubernetes
  config.vm.provision :shell, path: "k8s_base_vm.sh"

  # Configure the Master node
  config.vm.define "k8s-master" do |master|
    # set the machine name
    master.vm.hostname = "k8s-master"
    # set the private ip@
    master_ip = "#{START_IP}00"
    master.vm.network 'public_network', ip: "#{master_ip}"
    # dimension the VM
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = MASTER_CPU
      vb.memory = MASTER_MEM
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    # apply the master specific script
    master.vm.provision :shell, path: "k8s_bootstrap_master.sh"
  end

  # Configure the Slave nodes
  (1..NUM_NODES).each do |slave_number|

    # set the machine name
    slave_name = "k8s-slave#{slave_number}"
    # configure each slave machine
    config.vm.define slave_name do |node|
      # set the machine name
      node.vm.hostname = "#{slave_name}"
      # set the private ip@
      slave_address = 10 + slave_number
      slave_ip = "#{START_IP}#{slave_address}"
      node.vm.network 'public_network', ip: "#{slave_ip}"
        # dimension teh VM
      node.vm.provider 'virtualbox' do |vb|
        vb.cpus = SLAVE_CPU
        vb.memory = SLAVE_MEM
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
      # apply the master specific script
      node.vm.provision :shell, path: "k8s_bootstrap_slave.sh"
    end
  end

  # Cleanup temporary files
  # config.vm.provision :shell, path: "k8s_cleanup.sh"

end
